"""add owner_id and added_by fields

Revision ID: 73d8860557a7
Revises: 2de85716ac24
Create Date: 2025-12-12 13:30:32.608657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d8860557a7'
down_revision: Union[str, Sequence[str], None] = '2de85716ac24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_links')
    op.drop_table('livestock_production')
    op.drop_table('crop_growth')
    op.alter_column('activity_logs', 'farm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('crops', sa.Column('added_by', sa.Integer(), nullable=True))
    op.alter_column('crops', 'area_hectares',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.create_foreign_key(None, 'crops', 'users', ['added_by'], ['id'])
    op.add_column('inventory_items', sa.Column('added_by', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.create_foreign_key(None, 'inventory_items', 'users', ['added_by'], ['id'])
    op.add_column('livestock', sa.Column('added_by', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_livestock_id'), table_name='livestock')
    op.create_foreign_key(None, 'livestock', 'users', ['added_by'], ['id'])
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.add_column('transactions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_foreign_key(None, 'transactions', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_unique_constraint(None, 'users', ['firebase_uid'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_column('transactions', 'owner_id')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.drop_constraint(None, 'livestock', type_='foreignkey')
    op.create_index(op.f('ix_livestock_id'), 'livestock', ['id'], unique=False)
    op.drop_column('livestock', 'added_by')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.drop_column('inventory_items', 'added_by')
    op.drop_constraint(None, 'crops', type_='foreignkey')
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.alter_column('crops', 'area_hectares',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('crops', 'added_by')
    op.alter_column('activity_logs', 'farm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('crop_growth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('crop_growth_crop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crop_growth_pkey'))
    )
    op.create_table('livestock_production',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('livestock_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], name=op.f('livestock_production_livestock_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('livestock_production_pkey'))
    )
    op.create_table('expense_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('livestock_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('expense_links_crop_id_fkey')),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], name=op.f('expense_links_livestock_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('expense_links_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('expense_links_pkey'))
    )
    # ### end Alembic commands ###
