"""clean models and fix relationships

Revision ID: e165c61f35b2
Revises: 73d8860557a7
Create Date: 2025-12-16 16:31:50.551092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e165c61f35b2'
down_revision: Union[str, Sequence[str], None] = '73d8860557a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_growth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('livestock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livestock_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livestock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('crops_added_by_fkey'), 'crops', type_='foreignkey')
    op.drop_column('crops', 'added_by')
    op.drop_constraint(op.f('inventory_items_added_by_fkey'), 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'added_by')
    op.drop_constraint(op.f('livestock_added_by_fkey'), 'livestock', type_='foreignkey')
    op.drop_column('livestock', 'added_by')
    op.drop_constraint(op.f('transactions_owner_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'owner_id')
    op.alter_column('users', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'weekly_reports',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'weekly_reports',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('users', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.add_column('transactions', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('transactions_owner_id_fkey'), 'transactions', 'users', ['owner_id'], ['id'])
    op.add_column('livestock', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('livestock_added_by_fkey'), 'livestock', 'users', ['added_by'], ['id'])
    op.add_column('inventory_items', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_items_added_by_fkey'), 'inventory_items', 'users', ['added_by'], ['id'])
    op.add_column('crops', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('crops_added_by_fkey'), 'crops', 'users', ['added_by'], ['id'])
    op.drop_table('livestock_production')
    op.drop_table('expense_links')
    op.drop_table('crop_growth')
    # ### end Alembic commands ###
